"""Render the presentation-style PDF for Part II.

Style targets the look of the original Part I PDF: large colored title,
section-numbered hero bands, callout panels, side-by-side cards, and
embedded diagrams generated by build_diagrams.py.

Source: docs/E-Barber-System-CzescII.md (presentation-only text, no code).
"""
from __future__ import annotations

import re
from pathlib import Path

from reportlab.lib.colors import HexColor
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    HRFlowable,
    Image,
    KeepTogether,
    PageBreak,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)

# ------------------------------------------------------------------------ paths
DOC_DIR = Path(__file__).resolve().parent
SRC = DOC_DIR / "E-Barber-System-CzescII.md"
DEST = DOC_DIR / "E-Barber-System-CzescII.pdf"
IMG = DOC_DIR / "img"

# ------------------------------------------------------------------------ colors
TEAL = HexColor("#0F766E")
TEAL_DARK = HexColor("#115E59")
INK = HexColor("#17201D")
MUTED = HexColor("#66736E")
LINE = HexColor("#D9E0DC")
PANEL_SOFT = HexColor("#EEF4F1")
AMBER = HexColor("#B45309")
SOFT_GREEN = HexColor("#DCFCE7")
WHITE = HexColor("#FFFFFF")


# ------------------------------------------------------------------------ fonts
def register_fonts() -> tuple[str, str, str]:
    candidates = [
        ("Calibri", "calibri.ttf", "calibrib.ttf", "calibrii.ttf"),
        ("Segoe UI", "segoeui.ttf", "segoeuib.ttf", "segoeuii.ttf"),
        ("Arial", "arial.ttf", "arialbd.ttf", "ariali.ttf"),
    ]
    windows_fonts = Path("C:/Windows/Fonts")
    for name, reg, bold, italic in candidates:
        r = windows_fonts / reg
        b = windows_fonts / bold
        if r.exists() and b.exists():
            pdfmetrics.registerFont(TTFont(name, str(r)))
            pdfmetrics.registerFont(TTFont(f"{name}-Bold", str(b)))
            it = windows_fonts / italic
            pdfmetrics.registerFont(
                TTFont(f"{name}-Italic", str(it if it.exists() else r))
            )
            return name, f"{name}-Bold", f"{name}-Italic"
    return "Helvetica", "Helvetica-Bold", "Helvetica-Oblique"


FONT, FONT_BOLD, FONT_ITALIC = register_fonts()


# ------------------------------------------------------------------------ styles
def make_styles() -> dict[str, ParagraphStyle]:
    base = ParagraphStyle(
        name="Body",
        fontName=FONT,
        fontSize=11,
        leading=16,
        textColor=INK,
        alignment=TA_JUSTIFY,
        spaceAfter=8,
    )
    return {
        "body": base,
        "lead": ParagraphStyle(
            name="Lead",
            parent=base,
            fontSize=12.5,
            leading=18,
            spaceAfter=14,
            textColor=INK,
        ),
        "muted": ParagraphStyle(
            name="Muted",
            parent=base,
            textColor=MUTED,
            alignment=TA_LEFT,
            fontSize=10.5,
            leading=14,
        ),
        "h1": ParagraphStyle(
            name="H1",
            parent=base,
            fontName=FONT_BOLD,
            fontSize=28,
            leading=34,
            textColor=TEAL,
            alignment=TA_LEFT,
            spaceBefore=4,
            spaceAfter=8,
        ),
        "h2": ParagraphStyle(
            name="H2",
            parent=base,
            fontName=FONT_BOLD,
            fontSize=16,
            leading=22,
            textColor=TEAL_DARK,
            alignment=TA_LEFT,
            spaceBefore=12,
            spaceAfter=6,
        ),
        "h3": ParagraphStyle(
            name="H3",
            parent=base,
            fontName=FONT_BOLD,
            fontSize=13,
            leading=18,
            textColor=INK,
            alignment=TA_LEFT,
            spaceBefore=10,
            spaceAfter=2,
        ),
        "section_eyeline": ParagraphStyle(
            name="SectionEyeline",
            parent=base,
            fontName=FONT,
            fontSize=10,
            leading=12,
            textColor=AMBER,
            alignment=TA_LEFT,
            spaceAfter=2,
        ),
        "title": ParagraphStyle(
            name="Title",
            parent=base,
            fontName=FONT_BOLD,
            fontSize=44,
            leading=50,
            textColor=INK,
            alignment=TA_LEFT,
            spaceAfter=10,
        ),
        "subtitle": ParagraphStyle(
            name="Subtitle",
            parent=base,
            fontName=FONT_ITALIC,
            fontSize=15,
            leading=21,
            textColor=TEAL_DARK,
            alignment=TA_LEFT,
            spaceAfter=10,
        ),
        "tagline": ParagraphStyle(
            name="Tagline",
            parent=base,
            fontSize=11,
            leading=15,
            textColor=MUTED,
            alignment=TA_LEFT,
            spaceAfter=40,
        ),
        "bullet": ParagraphStyle(
            name="Bullet",
            parent=base,
            leftIndent=14,
            bulletIndent=0,
            spaceAfter=4,
            alignment=TA_LEFT,
        ),
        "toc_item": ParagraphStyle(
            name="TocItem",
            parent=base,
            fontName=FONT_BOLD,
            fontSize=12,
            leading=22,
            textColor=INK,
            alignment=TA_LEFT,
            spaceAfter=4,
        ),
        "toc_sub": ParagraphStyle(
            name="TocSub",
            parent=base,
            fontSize=10.5,
            leading=14,
            textColor=MUTED,
            alignment=TA_LEFT,
            leftIndent=16,
            spaceAfter=2,
        ),
        "caption": ParagraphStyle(
            name="Caption",
            parent=base,
            fontSize=9.5,
            leading=12,
            textColor=MUTED,
            alignment=TA_CENTER,
            spaceBefore=2,
            spaceAfter=14,
        ),
    }


STYLES = make_styles()


# ------------------------------------------------------------------------ inline
INLINE_RE = re.compile(r"(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`|_[^_]+_)")


def escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )


def render_inline(text: str) -> str:
    parts = []
    for chunk in INLINE_RE.split(text):
        if not chunk:
            continue
        if chunk.startswith("**") and chunk.endswith("**"):
            parts.append(f"<b>{escape(chunk[2:-2])}</b>")
        elif chunk.startswith("*") and chunk.endswith("*"):
            parts.append(f"<i>{escape(chunk[1:-1])}</i>")
        elif chunk.startswith("_") and chunk.endswith("_"):
            parts.append(f"<i>{escape(chunk[1:-1])}</i>")
        elif chunk.startswith("`") and chunk.endswith("`"):
            parts.append(f"<b>{escape(chunk[1:-1])}</b>")
        else:
            parts.append(escape(chunk))
    return "".join(parts)


# ------------------------------------------------------------------------ chrome
def chrome(canvas, doc):
    width, height = A4
    canvas.saveState()
    # Header band
    canvas.setFillColor(TEAL)
    canvas.rect(0, height - 14 * mm, width, 14 * mm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont(FONT_BOLD, 11)
    canvas.drawString(2 * cm, height - 9 * mm, "HairBook")
    canvas.setFont(FONT, 9.5)
    canvas.drawRightString(width - 2 * cm, height - 9 * mm, "E-Barber System — Część II")
    # Footer band
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.4)
    canvas.line(2 * cm, 15 * mm, width - 2 * cm, 15 * mm)
    canvas.setFillColor(MUTED)
    canvas.setFont(FONT, 8.5)
    canvas.drawString(2 * cm, 11 * mm, "Dokumentacja modelowania systemu — prezentacja 30.05.2026")
    canvas.drawRightString(width - 2 * cm, 11 * mm, f"strona {doc.page}")
    canvas.restoreState()


def cover_chrome(canvas, doc):
    width, height = A4
    canvas.saveState()
    # Big colored band on the left side
    canvas.setFillColor(TEAL)
    canvas.rect(0, 0, 3.4 * cm, height, fill=1, stroke=0)
    # Vertical typography
    canvas.setFillColor(WHITE)
    canvas.setFont(FONT_BOLD, 14)
    canvas.saveState()
    canvas.translate(2 * cm, 4 * cm)
    canvas.rotate(90)
    canvas.drawString(0, 0, "HAIRBOOK • E-BARBER SYSTEM • CZĘŚĆ II")
    canvas.restoreState()
    # Year badge bottom right
    canvas.setFillColor(TEAL_DARK)
    canvas.rect(width - 5 * cm, 0, 5 * cm, 2.6 * cm, fill=1, stroke=0)
    canvas.setFillColor(WHITE)
    canvas.setFont(FONT_BOLD, 18)
    canvas.drawCentredString(width - 2.5 * cm, 1.3 * cm, "30.05.2026")
    canvas.setFont(FONT, 8.5)
    canvas.drawCentredString(width - 2.5 * cm, 0.65 * cm, "PREZENTACJA")
    canvas.restoreState()


# ------------------------------------------------------------------------ panels
def callout_panel(text: str, *, color=TEAL, fill=PANEL_SOFT,
                  width=17 * cm) -> Table:
    """Branded callout box for important notes."""
    p = Paragraph(render_inline(text), STYLES["body"])
    table = Table([[p]], colWidths=[width])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, -1), fill),
                ("BOX", (0, 0), (-1, -1), 1.2, color),
                ("LEFTPADDING", (0, 0), (-1, -1), 14),
                ("RIGHTPADDING", (0, 0), (-1, -1), 14),
                ("TOPPADDING", (0, 0), (-1, -1), 12),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 12),
            ]
        )
    )
    return table


def numbered_section(number: str, title: str) -> Table:
    """Big colored section header with circled number badge."""
    badge = Paragraph(
        f'<para alignment="center"><font color="#FFFFFF" size="22"><b>{number}</b></font></para>',
        STYLES["body"],
    )
    title_para = Paragraph(
        f'<para alignment="left"><font color="#0F766E" size="26"><b>{escape(title)}</b></font></para>',
        STYLES["body"],
    )
    table = Table(
        [[badge, title_para]],
        colWidths=[1.8 * cm, 15.2 * cm],
        rowHeights=[1.8 * cm],
    )
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, 0), TEAL),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("TOPPADDING", (0, 0), (-1, -1), 0),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (1, 0), (1, 0), 16),
            ]
        )
    )
    return table


# ------------------------------------------------------------------------ builder
class PdfBuilder:
    def __init__(self):
        self.story: list = []
        self.section_count = 0
        self.section_emitted = False

    # ------------- cover -------------
    def add_cover(self):
        story = self.story
        story.append(Spacer(1, 18 * mm))
        story.append(Paragraph(
            '<font color="#B45309" size="11"><b>DOKUMENTACJA MODELOWANIA SYSTEMU</b></font>',
            STYLES["body"],
        ))
        story.append(Spacer(1, 14))
        story.append(Paragraph(
            '<font color="#17201D" size="56"><b>E-Barber</b></font>',
            ParagraphStyle("CoverTitle1", parent=STYLES["body"],
                           leading=62, spaceAfter=0, alignment=TA_LEFT),
        ))
        story.append(Paragraph(
            '<font color="#0F766E" size="56"><b>System</b></font>',
            ParagraphStyle("CoverTitle2", parent=STYLES["body"],
                           leading=62, spaceAfter=8, alignment=TA_LEFT),
        ))
        story.append(HRFlowable(width="35%", thickness=3, color=TEAL,
                                hAlign="LEFT", spaceBefore=4, spaceAfter=10))
        story.append(Paragraph(
            '<font color="#0F766E" size="26"><b>Część II</b></font>',
            ParagraphStyle("CoverPart", parent=STYLES["body"],
                           leading=30, alignment=TA_LEFT, spaceAfter=8),
        ))
        story.append(Paragraph(
            '<font color="#115E59" size="14"><i>Identyfikacja aktorów, '
            'przypadki użycia, analiza problemu, specyfikacja wymagań</i></font>',
            ParagraphStyle("CoverSub", parent=STYLES["body"],
                           leading=20, alignment=TA_LEFT, spaceAfter=16),
        ))
        story.append(Paragraph(
            '<font color="#66736E" size="11">Kontynuacja Części I — przejście od '
            'modelu opisowego do modelu wymagań i scenariuszy działania na '
            'podstawie implementacji aplikacji <b>HairBook Local</b>.</font>',
            ParagraphStyle("CoverTagline", parent=STYLES["body"],
                           leading=15, alignment=TA_JUSTIFY, spaceAfter=24),
        ))
        story.append(Spacer(1, 24))
        meta = Table(
            [[
                Paragraph(
                    '<font color="#66736E" size="9">PROJEKT</font><br/>'
                    '<font color="#17201D" size="13"><b>E-Barber System</b></font>',
                    STYLES["body"],
                ),
                Paragraph(
                    '<font color="#66736E" size="9">ROLE</font><br/>'
                    '<font color="#17201D" size="13"><b>Klient · Fryzjer · Admin</b></font>',
                    STYLES["body"],
                ),
                Paragraph(
                    '<font color="#66736E" size="9">MODUŁY</font><br/>'
                    '<font color="#17201D" size="13"><b>6 obszarów</b></font>',
                    STYLES["body"],
                ),
            ]],
            colWidths=[5 * cm, 5.5 * cm, 4 * cm],
            hAlign="LEFT",
        )
        meta.setStyle(TableStyle([
            ("LEFTPADDING", (0, 0), (-1, -1), 0),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 16),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 16),
            ("LINEABOVE", (0, 0), (-1, 0), 0.6, LINE),
            ("LINEBELOW", (0, 0), (-1, 0), 0.6, LINE),
        ]))
        story.append(meta)

    # ------------- toc -------------
    def add_toc(self):
        self.story.append(Paragraph("Spis treści", STYLES["h1"]))
        self.story.append(HRFlowable(width="100%", thickness=2, color=TEAL,
                                     spaceBefore=2, spaceAfter=18))
        entries = [
            ("01", "Wprowadzenie", []),
            ("02", "Identyfikacja aktorów", [
                "Aktorzy główni", "Aktorzy systemowi", "Hierarchia uprawnień",
            ]),
            ("03", "Katalog przypadków użycia", [
                "Klient", "Fryzjer", "Administrator",
            ]),
            ("04", "Wybrane scenariusze działania", [
                "Rezerwacja online", "Anulowanie wizyty",
                "Urlop fryzjera", "Zmiana statusu",
                "Nowe konto", "Edycja rezerwacji",
            ]),
            ("05", "Analiza problemu", []),
            ("06", "Specyfikacja wymagań", [
                "Funkcjonalne", "Niefunkcjonalne",
                "Kontrola ryzyka", "Weryfikacja",
            ]),
            ("07", "Model statyczny", [
                "Dekompozycja modułowa",
            ]),
            ("08", "Model dynamiczny", [
                "Cykl życia rezerwacji",
                "Diagram aktywności",
                "Diagram sekwencji",
            ]),
            ("09", "Analiza modeli interakcji", []),
            ("10", "Podsumowanie", []),
        ]
        for num, title, subs in entries:
            row = Table(
                [[
                    Paragraph(
                        f'<para alignment="center"><font color="#FFFFFF" size="10"><b>{num}</b></font></para>',
                        STYLES["body"],
                    ),
                    Paragraph(
                        (f'<font color="#17201D" size="12"><b>{escape(title)}</b></font>'
                         + (f'&nbsp;&nbsp;&nbsp;<font color="#66736E" size="9">{escape(" · ".join(subs))}</font>'
                            if subs else '')),
                        STYLES["body"],
                    ),
                ]],
                colWidths=[1.0 * cm, 16 * cm],
                rowHeights=[0.78 * cm],
            )
            row.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (0, 0), TEAL),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 0),
                ("RIGHTPADDING", (0, 0), (-1, -1), 0),
                ("LEFTPADDING", (1, 0), (1, 0), 12),
            ]))
            self.story.append(row)
            self.story.append(Spacer(1, 5))
        self.story.append(PageBreak())

    # ------------- markdown rendering -------------
    def parse_markdown(self, text: str):
        lines = text.splitlines()
        i = 0
        title_skipped = False

        while i < len(lines):
            line = lines[i]
            stripped = line.strip()

            if not stripped:
                i += 1
                continue

            heading = re.match(r"^(#{1,4})\s+(.*)$", stripped)
            if heading:
                level = len(heading.group(1))
                content = heading.group(2).strip()
                if level == 1 and not title_skipped:
                    title_skipped = True
                    i += 1
                    # skip the lead bold, italic, "Prezentacja", and the first ---
                    consumed_sep = False
                    while i < len(lines):
                        cur = lines[i].strip()
                        if not cur:
                            i += 1
                            continue
                        if cur.startswith("**") or cur.startswith("_") or cur.startswith("Prezentacja"):
                            i += 1
                            continue
                        if cur == "---" and not consumed_sep:
                            consumed_sep = True
                            i += 1
                            continue
                        break
                    continue
                if level == 2:
                    if self.section_emitted:
                        self.story.append(PageBreak())
                    self.add_section_header(content)
                    self.section_emitted = True
                elif level == 3:
                    self.story.append(Paragraph(escape(content), STYLES["h2"]))
                elif level == 4:
                    self.story.append(Paragraph(escape(content), STYLES["h3"]))
                else:
                    self.story.append(Paragraph(escape(content), STYLES["h2"]))
                i += 1
                continue

            if stripped == "---":
                # Visual separator handled by per-section page breaks; ignore.
                i += 1
                continue

            # Markdown image
            img_match = re.match(r"!\[([^\]]*)\]\(([^)]+)\)", stripped)
            if img_match:
                alt = img_match.group(1)
                path = img_match.group(2)
                self.add_image(path, alt)
                i += 1
                continue

            # Bullet block
            if stripped.startswith("- ") or stripped.startswith("* "):
                items = []
                while i < len(lines):
                    cur = lines[i].strip()
                    if cur.startswith("- ") or cur.startswith("* "):
                        items.append(cur[2:])
                        i += 1
                    elif not cur:
                        break
                    else:
                        break
                for item in items:
                    self.story.append(Paragraph(
                        f'<font color="#0F766E"><b>•</b></font>&nbsp;&nbsp;{render_inline(item)}',
                        STYLES["bullet"],
                    ))
                self.story.append(Spacer(1, 6))
                continue

            # Paragraph
            block = [stripped]
            i += 1
            while i < len(lines):
                follow = lines[i].rstrip()
                if not follow.strip():
                    break
                if follow.lstrip().startswith(("#", "|", "- ", "* ", "---", "![")):
                    break
                block.append(follow.strip())
                i += 1
            text = " ".join(block)
            if text.startswith("_") and text.endswith("_"):
                self.story.append(Paragraph(
                    f'<font color="#66736E"><i>{escape(text[1:-1])}</i></font>',
                    STYLES["body"],
                ))
            else:
                self.story.append(Paragraph(render_inline(text), STYLES["body"]))

    # ------------- atoms -------------
    def add_section_header(self, raw_title: str):
        match = re.match(r"^(\d+)\.\s+(.*)$", raw_title)
        if match:
            number = match.group(1).zfill(2)
            title = match.group(2)
        else:
            self.section_count += 1
            number = f"{self.section_count:02d}"
            title = raw_title
        self.story.append(Spacer(1, 4))
        self.story.append(numbered_section(number, title))
        self.story.append(Spacer(1, 10))

    def add_image(self, path: str, alt: str):
        full = (DOC_DIR / path).resolve()
        if not full.exists():
            self.story.append(Paragraph(
                f"<i>[Brak obrazu: {escape(path)}]</i>",
                STYLES["muted"],
            ))
            return
        # Constrain so the image leaves room for following text on the page.
        from reportlab.lib.utils import ImageReader
        reader = ImageReader(str(full))
        iw, ih = reader.getSize()
        ratio = ih / iw
        target_width = 15 * cm
        height = target_width * ratio
        max_height = 10 * cm
        if height > max_height:
            height = max_height
            target_width = height / ratio
        img = Image(str(full), width=target_width, height=height, hAlign="CENTER")
        wrapper = KeepTogether([
            Spacer(1, 4),
            img,
            Paragraph(escape(alt) if alt else "", STYLES["caption"]),
        ])
        self.story.append(wrapper)

    # ------------- build -------------
    def build(self, dest: Path, cover_story, rest_story):
        doc = BaseDocTemplate(
            str(dest),
            pagesize=A4,
            leftMargin=2 * cm,
            rightMargin=2 * cm,
            topMargin=2.2 * cm,
            bottomMargin=2.2 * cm,
            title="E-Barber System — Część II",
            author="Zespół HairBook",
            subject="Dokumentacja modelowania systemu",
        )

        cover_frame = Frame(
            3.8 * cm, 3 * cm,
            A4[0] - 3.8 * cm - 2 * cm, A4[1] - 4 * cm,
            id="cover", showBoundary=0,
        )
        content_frame = Frame(
            2 * cm, 2.2 * cm,
            A4[0] - 4 * cm, A4[1] - 4.4 * cm,
            id="content", showBoundary=0,
        )
        cover_tpl = PageTemplate(id="cover", frames=[cover_frame], onPage=cover_chrome)
        content_tpl = PageTemplate(id="content", frames=[content_frame], onPage=chrome)
        doc.addPageTemplates([cover_tpl, content_tpl])

        from reportlab.platypus.doctemplate import NextPageTemplate
        story = [
            *cover_story,
            NextPageTemplate("content"),
            PageBreak(),
            *rest_story,
        ]
        doc.build(story)


def main() -> int:
    if not SRC.exists():
        print(f"Source missing: {SRC}")
        return 1

    # Cover
    cover_builder = PdfBuilder()
    cover_builder.add_cover()
    cover = cover_builder.story

    # Rest (TOC + content)
    builder = PdfBuilder()
    builder.add_toc()
    builder.parse_markdown(SRC.read_text(encoding="utf-8"))
    rest = builder.story

    PdfBuilder().build(DEST, cover, rest)
    print(f"Saved {DEST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
