import { normalizeDateInput } from "./core.js";

export const initialData = {
  salon: {
    name: "HairBook Barber Studio",
    city: "Warszawa",
    address: "ul. Brzeska 18",
    phone: "+48 501 204 300",
    email: "kontakt@hairbook.local",
    plan: "Pro",
    rating: 4.8,
    reviewCount: 184,
    openHour: 9,
    closeHour: 19,
    slotStep: 30,
    onboarding: {
      services: true,
      staff: true,
      firstBooking: true,
      profile: true,
    },
  },
  users: [
    {
      id: "admin-1",
      role: "admin",
      name: "Marta Zalewska",
      email: "marta@hairbook.local",
    },
    {
      id: "barber-1",
      role: "barber",
      name: "Oskar Wrona",
      email: "oskar@hairbook.local",
    },
    {
      id: "client-1",
      role: "client",
      name: "Adam Nowak",
      email: "adam@example.com",
    },
  ],
  staff: [
    {
      id: "barber-1",
      name: "Oskar Wrona",
      title: "Senior barber",
      specialty: "Skin fade i klasyczne cięcia",
      active: true,
      workDays: [1, 2, 3, 4, 5],
      color: "#0f766e",
    },
    {
      id: "barber-2",
      name: "Igor Maj",
      title: "Barber",
      specialty: "Broda, kontur, styling",
      active: true,
      workDays: [2, 3, 4, 5, 6],
      color: "#b45309",
    },
    {
      id: "barber-3",
      name: "Tymon Kruk",
      title: "Junior barber",
      specialty: "Strzyżenie podstawowe",
      active: true,
      workDays: [1, 3, 5, 6],
      color: "#2563eb",
    },
  ],
  services: [
    {
      id: "service-cut",
      name: "Strzyżenie męskie",
      category: "Włosy",
      duration: 45,
      price: 80,
      active: true,
      description: "Konsultacja, strzyżenie, mycie i stylizacja.",
    },
    {
      id: "service-fade",
      name: "Skin fade",
      category: "Włosy",
      duration: 60,
      price: 100,
      active: true,
      description: "Precyzyjne cieniowanie z wykończeniem brzytwą.",
    },
    {
      id: "service-beard",
      name: "Trymowanie brody",
      category: "Broda",
      duration: 30,
      price: 55,
      active: true,
      description: "Kontur, trymowanie i pielęgnacja gorącym ręcznikiem.",
    },
    {
      id: "service-combo",
      name: "Combo: włosy + broda",
      category: "Pakiet",
      duration: 75,
      price: 135,
      active: true,
      description: "Pełna wizyta barberska dla stałego klienta.",
    },
  ],
  clients: [
    {
      id: "client-1",
      name: "Adam Nowak",
      phone: "501 100 200",
      email: "adam@example.com",
      notes: "Preferuje fade i matową pastę.",
      tags: ["stały klient"],
      lastVisit: normalizeDateInput("2026-05-03", "12:00"),
    },
    {
      id: "client-2",
      name: "Marek Kowalski",
      phone: "502 300 400",
      email: "marek@example.com",
      notes: "Wrażliwa skóra po goleniu.",
      tags: ["broda"],
      lastVisit: normalizeDateInput("2026-05-10", "16:00"),
    },
    {
      id: "client-3",
      name: "Filip Baran",
      phone: "503 200 100",
      email: "filip@example.com",
      notes: "Przychodzi co 3 tygodnie.",
      tags: ["online"],
      lastVisit: normalizeDateInput("2026-04-26", "10:00"),
    },
    {
      id: "client-4",
      name: "Kamil Lis",
      phone: "504 440 550",
      email: "kamil@example.com",
      notes: "Lubi poranne terminy.",
      tags: ["nowy"],
      lastVisit: "",
    },
  ],
  bookings: [
    {
      id: "booking-1001",
      clientId: "client-1",
      barberId: "barber-1",
      serviceId: "service-fade",
      startsAt: normalizeDateInput("2026-05-18", "09:00"),
      endsAt: normalizeDateInput("2026-05-18", "10:00"),
      status: "confirmed",
      source: "online",
      notes: "Klient prosi o ciche powiadomienie SMS.",
      createdAt: normalizeDateInput("2026-05-15", "11:20"),
    },
    {
      id: "booking-1002",
      clientId: "client-2",
      barberId: "barber-2",
      serviceId: "service-combo",
      startsAt: normalizeDateInput("2026-05-18", "10:30"),
      endsAt: normalizeDateInput("2026-05-18", "11:45"),
      status: "confirmed",
      source: "frontdesk",
      notes: "",
      createdAt: normalizeDateInput("2026-05-16", "15:00"),
    },
    {
      id: "booking-1003",
      clientId: "client-3",
      barberId: "barber-1",
      serviceId: "service-cut",
      startsAt: normalizeDateInput("2026-05-18", "13:00"),
      endsAt: normalizeDateInput("2026-05-18", "13:45"),
      status: "confirmed",
      source: "online",
      notes: "Bez mycia.",
      createdAt: normalizeDateInput("2026-05-16", "17:00"),
    },
    {
      id: "booking-1004",
      clientId: "client-1",
      barberId: "barber-1",
      serviceId: "service-combo",
      startsAt: normalizeDateInput("2026-05-03", "12:00"),
      endsAt: normalizeDateInput("2026-05-03", "13:15"),
      status: "completed",
      source: "frontdesk",
      notes: "Udana wizyta, zaproponowac nastepny termin.",
      createdAt: normalizeDateInput("2026-04-28", "09:10"),
    },
    {
      id: "booking-1005",
      clientId: "client-2",
      barberId: "barber-2",
      serviceId: "service-beard",
      startsAt: normalizeDateInput("2026-05-10", "16:00"),
      endsAt: normalizeDateInput("2026-05-10", "16:30"),
      status: "completed",
      source: "online",
      notes: "",
      createdAt: normalizeDateInput("2026-05-01", "18:00"),
    },
  ],
  notifications: [
    {
      id: "notice-1",
      type: "booking",
      title: "Nowa rezerwacja online",
      message: "Adam Nowak zarezerwował Skin fade u Oskara.",
      createdAt: normalizeDateInput("2026-05-15", "11:20"),
      read: false,
    },
    {
      id: "notice-2",
      type: "system",
      title: "Brak płatności w MVP",
      message: "Moduł płatności jest celowo wyłączony w lokalnej wersji aplikacji.",
      createdAt: normalizeDateInput("2026-05-17", "09:00"),
      read: false,
    },
    {
      id: "notice-3",
      type: "risk",
      title: "Kontrola double-bookingu",
      message: "System blokuje nakładające się wizyty tego samego fryzjera.",
      createdAt: normalizeDateInput("2026-05-17", "09:10"),
      read: true,
    },
  ],
};

export function cloneInitialData() {
  return structuredClone(initialData);
}
